### ISSUE TITLE
Document direction of changes

### ISSUE THREAD

**Issue by ghost** [k4j8/filetailor#1]
I believe the following facts should be made explicit in the documentation. Maybe you have fallen in the typical developer trap and they seem obvious to you, but they aren't and I would have avoided much frustration had I known. This happens to me all the time on programs I myself write, of course. So:

1. `filetailor backup` *only* comments out the blocks conditional to the current device, and doesn't uncomment anything,
2. `filetailor restore` *only* uncomments the blocks conditional to the current device, and doesn't comment out anything.

I hope I got it right.

Thanks for a great idea, btw! A passage between the Scylla of undisciplined proliferating versions of dotfiles and the Charybdis of keeping them in git -- one branch per host -- was badly needed.

**Comment by k4j8** [comment]
Thanks for the feedback. Yes, you got it right, both how the commands work and that I have fallen down the typical developer trap of tunnel vision. As you said, `filetailor backup` comments out blocks/lines for the current device and also replaces any variable values for that device with the variable name (if any are defined) but nothing gets uncommented. If you want to write code for a device other than the one you are on, you'll need to place those lines in a filetailor block and comment them out manually.

I created PR #2 with proposed changes if you have suggestions, otherwise I'll merge shortly.

**Comment by k4j8** [comment]
I'm trying to hit the documentation sweet spot where I don't overwhelm potential users with a long, intimidating README but also have enough enough information for them to understand what the tool actually does. If you have any other feedback ― vague or specific ― please let me know.

FYI, while I use this package daily without issue, it hasn't been tested by anyone else and probably has issues somewhere in the code.
